language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

install:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml --configuration tests/phpunit.xml.dist.xml

after_script:
 - vendor/bin/coveralls -v
